mixer:
  master:
    volume: 1
    fxs:
      - limiter:
          name: master-limiter
          maxVolume: 0.95
  channels:
    - name: drums
      volume: 1
    - name: perc
      volume: 1
      sends:
        - channel: reverb-bus
          gain: 0.7
    - name: bass
      volume: 1
    - name: pad
      volume: 1
      sends:
        - channel: reverb-bus
          gain: 0.2
    - name: glue
      volume: 1
    - volume: 1
    - volume: 1
    - volume: 1
      name: reverb-bus
      fxs:
        - reverb:
            name: reverb-bus
            size: 0.9
            damp: 0.8
            dryWet: 1

sampler:
  dir: "../tracks"
  tracks :
    - name: "La melody"
      dir: "LaMelodyStems_85bpm"
      stems:
        - file: "Arps.wav"
          channel: 4
        - file: "Kick.wav"
          channel: 1
        - file: "Piano.wav"
          channel: 4
        - file: "Bass.wav"
          channel: 3
        - file: "KoraFull.wav"
          channel: 5
        - file: "Snare.wav"
          channel: 1
        - file: "Flute.wav"
          channel: 5
        - file: "Ngoni.wav"
          channel: 6
        - file: "Strings.wav"
          channel: 6
        - file: "Kalimba.wav"
          channel: 5
        - file: "Ohs+Room.wav"
          channel: 2
        - file: "Tom.wav"
          channel: 2
        - file: "Kalimba2.wav"
          channel: 5
        - file: "Percussion.wav"
          channel: 2
        - file: "Vibraphone.wav"
          channel: 5
      slots:
        - bpm: 85
          measure: [4, 4]
          changeRate: 4
          cues:
            - dur: 16
            - dur: 32
            - dur: 32

    - name: "Never Enough"
      dir: "NE_Stems_85bpm"
      stems:
        - file: "Arp.wav"
          channel: 4
        - file: "MainSample.wav"
          channel: 4
        - file: "Atmo.wav"
          channel: 7
        - file: "Percussion.wav"
          channel: 2
        - file: "Bass.wav"
          channel: 3
        - file: "Piano.wav"
          channel: 4
        - file: "DrumLoop.wav"
          channel: 1
        - file: "RevGtrs.wav"
          channel: 4
        - file: "Flute.wav"
          channel: 6
        - file: "Shaker+Tamburine.wav"
          channel: 2
        - file: "Gtrs.wav"
          channel: 5
        - file: "Strings.wav"
          channel: 4
        - file: "Hats.wav"
          channel: 2
        - file: "VocalsSample.wav"
          channel: 4
      slots:
        - bpm: 85
          measure: [4, 4]
          changeRate: 8
          cues:
            - dur: 16
            - dur: 16
            - dur: 8

    - name: "Samurai"
      dir: "SamuraiStems119bpm"
      stems:
        - file: "Bansuri.wav"
          channel: 4
        - file: "FilterHats.wav"
          channel: 2
        - file: "Pads+Atmos.wav"
          channel: 6
        - file: "Rim+Clap.wav"
          channel: 1
        - file: "Vibraphone.wav"
          channel: 4
        - file: "Bass.wav"
          channel: 3
        - file: "Kick.wav"
          channel: 1
        - file: "Percussion.wav"
          channel: 2
        - file: "Shamisen.wav"
          channel: 4
        - file: "CinematicSamples.wav"
          channel: 6
        - file: "OffbeatHats.wav"
          channel: 2
        - file: "RevDholak.wav"
          channel: 2
        - file: "Snaps.wav"
          channel: 2
      slots:
        - bpm: 119
          measure: [4, 4]
          changeRate: 4
          cues:
            - dur: 16
              nextAction: "next"
            - dur: 16
              nextAction: "next"
            - dur: 12
              nextAction: "next"
            - dur: 64

# audio:
#   csound: put-csound-flags-gere
controllers:
  midi:
    # names for Akai MIDI MIX controller
    keys:
      slider1: 19
      slider2: 23
      slider3: 27
      slider4: 31
      slider5: 49
      slider6: 53
      slider7: 57
      slider8: 61
      sliderMaster: 62
      mute1: 1
      mute2: 4
      mute3: 7
      mute4: 10
      mute5: 13
      mute6: 16
      mute7: 19
      mute8: 22
      solo: 27
      bankRight: 26
      bankLeft: 25
      knob11: 16
      knob21: 20
      knob31: 24
      knob41: 28
      knob51: 46
      knob61: 50
      knob71: 54
      knob81: 58
      knob12: 17
      knob22: 21
      knob32: 25
      knob42: 29
      knob52: 47
      knob62: 51
      knob72: 55
      knob82: 59
      knob13: 18
      knob23: 22
      knob33: 26
      knob43: 30
      knob53: 48
      knob63: 52
      knob73: 56
      knob83: 60

    modifiers:
      shift:
        key: 27

    knobs:
      - when:
          key: sliderMaster
        act:
          - on: "masterVolume"
      - when:
          key: slider1
        act:
          - on:
              channelVolume: 1
      - when:
          key: slider2
        act:
          - on:
              channelVolume: 2
      - when:
          key: slider3
        act:
          - on:
              channelVolume: 3
      - when:
          key: slider4
        act:
          - on:
              channelVolume: 4
      - when:
          key: slider5
        act:
          - on:
              channelVolume: 5
      - when:
          key: slider6
        act:
          - on:
              channelVolume: 6
      - when:
          key: slider7
        act:
          - on:
              channelVolume: 7
      - when:
          key: slider8
        act:
          - on:
              channelVolume: 8

      - when:
          key: 18
        act:
          - on:
              fxParam:
                name: drum-delay-1
                param: dryWet

      - when:
          key: 17
        act:
          - on:
              fxParam:
                name: drum-delay-2
                param: dryWet

      - when:
          key: 16
        act:
          - on:
              fxParam:
                name: drum-delay-3
                param: dryWet

      - when:
          key: 22
        act:
          - on:
              fxParam:
                name: drum-filter
                param: cutoff

      - when:
          key: 21
        act:
          - on:
              fxParam:
                name: drum-filter
                param: resonance

      - when:
          key: 60
        act:
          - on:
              channelSend:
                from: 2
                to: 8
          - on:
              channelSend:
                from: 4
                to: 8

    notes:
      - when:
          key: 25
        act:
          - shiftPart: -1
      - when:
          key: 26
        act:
          - shiftPart: 1
      - when:
          key: 25
          modifier: shift
        act:
          - shiftTrack: -1
      - when:
          key: 26
          modifier: shift
        act:
          - shiftTrack: 1
      - when:
          key: 3
          modifier: shift
        act:
          - track: 1
      - when:
          key: 6
          modifier: shift
        act:
          - track: 2
      - when:
          key: 9
          modifier: shift
        act:
          - track: 3

      - when:
          key: 1
        act:
          - mute: 1

      - when:
          key: 4
        act:
          - mute: 2

      - when:
          key: 7
        act:
          - mute: 3

      - when:
          key: 10
        act:
          - mute: 4

      - when:
          key: 13
        act:
          - mute: 5

      - when:
          key: 16
        act:
          - mute: 6

      - when:
          key: 19
        act:
          - mute: 7

      - when:
          key: 22
        act:
          - mute: 8
