mixer:
  master:
    volume: 1
    fxs:
      - limiter:
          name: master-limiter
          maxVolume: 0.95
  channels:
    - volume: 1
      fxs:
        - delay:
            name: drum-delay-1
            repeatTime: 0.5
            damp: 0.8
            feedback: 0.2
            dryWet: 0.0
        - delay:
            name: drum-delay-2
            repeatTime: 1
            damp: 0.6
            feedback: 0.3
            dryWet: 0.0
        - delay:
            name: drum-delay-3
            repeatTime: 2
            damp: 0.6
            feedback: 0.3
            dryWet: 0.0

        - moogFilter:
            name: drum-filter
            cutoff: 1
            resonance: 0
            dryWet: 1

    - volume: 1
    - volume: 1
    - volume: 1
    - volume: 1
    - volume: 1
    - volume: 1
    - volume: 1

sampler:
  dir: "../tracks"
  tracks :
    - name: "La melody"
      dir: "LaMelodyStems_85bpm"
      stems:
        - file: "Arps.wav"
          channel: 4
        - file: "Kick.wav"
          channel: 1
        - file: "Piano.wav"
          channel: 4
        - file: "Bass.wav"
          channel: 3
        - file: "KoraFull.wav"
          channel: 5
        - file: "Snare.wav"
          channel: 1
        - file: "Flute.wav"
          channel: 5
        - file: "Ngoni.wav"
          channel: 6
        - file: "Strings.wav"
          channel: 6
        - file: "Kalimba.wav"
          channel: 5
        - file: "Ohs+Room.wav"
          channel: 2
        - file: "Tom.wav"
          channel: 2
        - file: "Kalimba2.wav"
          channel: 5
        - file: "Percussion.wav"
          channel: 2
        - file: "Vibraphone.wav"
          channel: 5
      slots:
        - bpm: 85
          measure: [4, 4]
          changeRate: 4
          cues:
            - dur: 16
            - dur: 32
            - dur: 32

    - name: "Never Enough"
      dir: "NE_Stems_85bpm"
      stems:
        - file: "Arp.wav"
          channel: 4
        - file: "MainSample.wav"
          channel: 4
        - file: "Atmo.wav"
          channel: 7
        - file: "Percussion.wav"
          channel: 2
        - file: "Bass.wav"
          channel: 3
        - file: "Piano.wav"
          channel: 4
        - file: "DrumLoop.wav"
          channel: 1
        - file: "RevGtrs.wav"
          channel: 4
        - file: "Flute.wav"
          channel: 6
        - file: "Shaker+Tamburine.wav"
          channel: 2
        - file: "Gtrs.wav"
          channel: 5
        - file: "Strings.wav"
          channel: 4
        - file: "Hats.wav"
          channel: 2
        - file: "VocalsSample.wav"
          channel: 4
      slots:
        - bpm: 85
          measure: [4, 4]
          changeRate: 8
          cues:
            - dur: 16
            - dur: 16
            - dur: 8

    - name: "Samurai"
      dir: "SamuraiStems119bpm"
      stems:
        - file: "Bansuri.wav"
          channel: 4
        - file: "FilterHats.wav"
          channel: 2
        - file: "Pads+Atmos.wav"
          channel: 6
        - file: "Rim+Clap.wav"
          channel: 1
        - file: "Vibraphone.wav"
          channel: 4
        - file: "Bass.wav"
          channel: 3
        - file: "Kick.wav"
          channel: 1
        - file: "Percussion.wav"
          channel: 2
        - file: "Shamisen.wav"
          channel: 4
        - file: "CinematicSamples.wav"
          channel: 6
        - file: "OffbeatHats.wav"
          channel: 2
        - file: "RevDholak.wav"
          channel: 2
        - file: "Snaps.wav"
          channel: 2
      slots:
        - bpm: 119
          measure: [4, 4]
          changeRate: 4
          cues:
            - dur: 16
              nextAction: "next"
            - dur: 16
              nextAction: "next"
            - dur: 12
              nextAction: "next"
            - dur: 64

audio: "audio"
controllers:
  midi:
    modifiers:
      shift:
        key: 27

    knobs:
      - when:
          key: 62
        act:
          - on: "masterVolume"
      - when:
          key: 19
        act:
          - on:
              channelVolume: 1
      - when:
          key: 23
        act:
          - on:
              channelVolume: 2
      - when:
          key: 27
        act:
          - on:
              channelVolume: 3
      - when:
          key: 31
        act:
          - on:
              channelVolume: 4
      - when:
          key: 31
        act:
          - on:
              channelVolume: 5
      - when:
          key: 49
        act:
          - on:
              channelVolume: 6
      - when:
          key: 53
        act:
          - on:
              channelVolume: 7
      - when:
          key: 61
        act:
          - on:
              channelVolume: 8

      - when:
          key: 18
        act:
          - on:
              fxParam:
                name: drum-delay-1
                param: dryWet

      - when:
          key: 17
        act:
          - on:
              fxParam:
                name: drum-delay-2
                param: dryWet

      - when:
          key: 16
        act:
          - on:
              fxParam:
                name: drum-delay-3
                param: dryWet

      - when:
          key: 22
        act:
          - on:
              fxParam:
                name: drum-filter
                param: cutoff

      - when:
          key: 21
        act:
          - on:
              fxParam:
                name: drum-filter
                param: resonance

    notes:
      - when:
          key: 25
        act:
          - shiftPart: -1
      - when:
          key: 26
        act:
          - shiftPart: 1
      - when:
          key: 25
          modifier: shift
        act:
          - shiftTrack: -1
      - when:
          key: 26
          modifier: shift
        act:
          - shiftTrack: 1
      - when:
          key: 3
          modifier: shift
        act:
          - track: 1
      - when:
          key: 6
          modifier: shift
        act:
          - track: 2
      - when:
          key: 9
          modifier: shift
        act:
          - track: 3

      - when:
          key: 1
        act:
          - mute: 1

      - when:
          key: 4
        act:
          - mute: 2

      - when:
          key: 7
        act:
          - mute: 3

      - when:
          key: 10
        act:
          - mute: 4

      - when:
          key: 13
        act:
          - mute: 5

      - when:
          key: 16
        act:
          - mute: 6

      - when:
          key: 19
        act:
          - mute: 7

      - when:
          key: 22
        act:
          - mute: 8
