resolver:
  nightly-2024-06-13
  #  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/11.yaml

packages:
  - packages/csound-live-sampler
  - packages/csound-live-sampler-osc-client

extra-deps:
  -  ../csound-expression/packages/core/csound-expression-dynamic
  -  ../csound-expression/packages/core/csound-core-types
  -  ../csound-expression/packages/core/csound-core-opcodes
  -  ../csound-expression/packages/core/csound-core-base
  -  ../csound-expression/packages/core/csound-core
    # - git: https://github.com/spell-music/csound-expression
    # commit: f80dc5125dd46766c93688c283bd9f9ba2c466f0
    # subdirs:
    #     - packages/core/csound-expression-dynamic
    #     - packages/core/csound-core

  - git: https://github.com/spell-music/data-fix-cse
    commit: abff72605479401fc43fa62f053153a11d7a1c61

  - temporal-media-0.6.3@sha256:7a27d711a786c3dc9163433627e51efcc4b3fce3a947b71c29f3e388f37cae59,857

notify-if-nix-on-path: false
