resolver:
  lts-22.11
  #  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/11.yaml

packages:
- .

extra-deps:
  # -  ../csound-expression/packages/core/csound-expression-dynamic
  # -  ../csound-expression/packages/core/csound-core
  - git: https://github.com/spell-music/csound-expression
    commit: f80dc5125dd46766c93688c283bd9f9ba2c466f0
    subdirs:
        - packages/core/csound-expression-dynamic
        - packages/core/csound-core

  - git: https://github.com/spell-music/data-fix-cse
    commit: abff72605479401fc43fa62f053153a11d7a1c61
